# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: app-name-service
spec:
  selector:
    app: app-name-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort